apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "sparklmsdb"
            - name: MYSQL_USER
              value: "dbshi"
            - name: MYSQL_PASSWORD
              value: "db@127"
          ports:
            - containerPort: 3306
