apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: post-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
  type: NodePort